config/routes.rb
Slowmail::Application.routes.draw do

   match 'auth/:provider/callback', to: 'sessions#create'
   match 'auth/failure', to: redirect('/')
   match 'logout', to: 'sessions#destroy', as: 'logout'

   match 'draft', to: 'letters#draft', as: 'draft'
   match 'random', to: 'web#random', as: 'random'

   match 'save_draft', to: 'letters#save_draft', as: 'save_draft'
   match 'mail_letter', to: 'letters#mail_letter', as: 'mail_letter'

   match 'my_drafts', to: 'users#my_drafts', as: 'my_drafts'

   match 'about', to: 'web#about', as: 'about'
   match 'terms', to: 'web#terms', as: 'terms'
   match 'privacy', to: 'web#privacy', as: 'privacy'

   match '/with/:username', to: 'letters#index', as: 'letters_index', :username => /[A-Za-z0-9\.]+?/, :format => /json|csv|xml|yaml/, :method=>:get
   match '/with/:username/reply', to: 'letters#draft', as: 'letters_reply', :username => /[A-Za-z0-9\.]+?/, :format => /json|csv|xml|yaml/, :method=>:get

   match '/letter/:id/deliver_now', to: 'letters#deliver_now'


   match 'envelope', to: 'web#envelope', as: 'envelope'


   root :to => 'web#home'





   resources :letters

end

app/models/letter.rb
class Letter < ActiveRecord::Base
    attr_accessible :anonymous, :author_id, :content, :delivery_date, :delivery_method, :email, :hearts_count, :nickname, :private, :receiver_id, :salutation, :unread, :views_count, :city

    before_destroy :update_sidebar_on_destroy 

    has_many :subscribed_letters, :dependent => :destroy
    has_many :recipients, :through=>:subscribed_letters, :source => :user
    belongs_to :author, :class_name => "User"

    scope :order_by_date, :order => "mailed_at desc"
    scope :not_delivered, where(delivered: [false, nil])
    scope :delivered, :conditions=>["delivered = ?",true]
    scope :time_for_delivery, :conditions=>["mailed = ? and delivery_date < ?",true,Time.now]

    scope :draft_for, (lambda do |current_user,tag| 
      where(["mailed = ? and author_id = ? and tag = ?",false,current_user.id,tag]) 
    end)

  	scope :received_or_sent, (lambda do |my_id,other_id| 
  		joins(:subscribed_letters).where(["letters.mailed = ? and to_count = 1 and ((subscribed_letters.user_id = ? and author_id = ?) or (author_id = ? and subscribed_letters.user_id = ?))",true,my_id,other_id,my_id,other_id]) 
  	end)

    scope :letters_received_or_sent_for, (lambda do |my_id| 
      joins(:subscribed_letters).where(["letters.mailed = ? and (subscribed_letters.user_id = ? or author_id = ?)",true,my_id,my_id]) 
    end)

  	scope :matching_tag, (lambda do |tag| 
  		where(["mailed = ? and tag=?",true,tag]) 
  	end)

   #after_create :update_sidebar_for_author

	def writing_partners(current_user)
	  user_avatars = self.recipients.pluck(:avatar)
		user_avatars.push(self.author.avatar)
		user_avatars.delete(current_user.avatar)
		unless current_user.id == self.author.id
			user_avatars.reverse
		end
		user_avatars
	end

  def writing_partner_names(current_user)
    user_names = self.recipients.pluck(:first_name)
    user_names.push(self.author.first_name)
    user_names.delete(current_user.first_name)
    unless current_user.id == self.author.id
      user_names.reverse
    end
    user_names.to_sentence.gsub("and","&")
  end

  def writing_partner_ids(current_user)
    user_names = self.recipients.pluck(:id)
    user_names.push(self.author.id)
    user_names.delete(current_user.id)
    user_names
  end

  def letter_url_for(current_user)
    if self.recipients.length == 1
      if self.author.id == current_user.id
        url = "/with/#{self.recipients[0].username}"
      else
        url = "/with/#{self.author.username}"
      end
    else
      url = "/with/#{self.tag}"
    end
  end

  def get_participant_ids
    participant_array = []
    participant_array.push(self.author.id.to_i)
    for user in self.recipients
      participant_array.push(user.id.to_i)
    end
    participant_array.sort!
    participant_ids = participant_array.join(",")
    participant_ids
  end


  

  def update_sidebar_for_author

    if self.recipients.count == 1
      message_count = Letter.received_or_sent(self.author_id,self.recipients[0].id).count
    else
      message_count = Letter.matching_tag(self.tag)
    end

    sidebar = Conversation.where(:sidebar_owner_id => self.author_id, :cc_user_ids => self.participant_ids).first_or_initialize

    sidebar.update_attributes(
     :last_letter_id => self.id,
     :unread => false,
     :message_count => message_count
    )
    sidebar.save

  end


  def update_sidebar_for_reader

    if self.recipients.count == 1
      message_count = Letter.received_or_sent(self.author_id,self.recipients[0].id).count
    else
      message_count = Letter.matching_tag(self.tag)
    end

    for user in self.recipients
      sidebar = Conversation.where(:sidebar_owner_id => user.id, :cc_user_ids => self.participant_ids).first_or_initialize

      sidebar.update_attributes(
        :last_letter_id => self.id,
        :unread => true,
        :message_count => message_count
      )
      sidebar.save

    end

  end

  def update_sidebar_on_destroy
      @conversations = Conversation.find(:all, :conditions=>["last_letter_id = ?",self.id])
      if @conversations.count > 0
        if self.recipients.count == 1
          @letters = Letter.received_or_sent(self.author_id,self.recipients[0].id)
        else
          @letters = Letter.matching_tag(self.tag)
        end
      end

      for sidebar in @conversations
        if @letters.count > 1
          sidebar.last_letter_id = @letters[0].id
          sidebar.save
        else
          sidebar.destroy
        end
      end

  end

  def deliver_letter
      self.delivery_date = Time.now
      self.delivered = true
      self.save!
      self.update_sidebar_for_reader

      for recipient in self.recipients
        begin
          result = SendWithUs::Api.new.send_with('tem_Es7Dmca87rdSgMSoUJp8SJ', { address: recipient.email }, { company_name: 'TestCo' })
          puts result
        rescue => e
          puts "Error - #{e.class.name}: #{e.message}"
        end
      end

  end




end

app/controllers/letters_controller.rb
class LettersController < ApplicationController

  before_filter :authenticate



  def index

    if params[:username]

      @user = User.find_by_username(params[:username])

      if @user
        @letters = Letter.received_or_sent(current_user.id,@user).order_by_date
        @page_title = "#{@user.first_name} #{@user.last_name}"
      else
        @letters = Letter.matching_tag(params[:username]).order_by_date
        if @letters and @letters.length > 0 and current_user
          @page_title = @letters[0].writing_partner_names(current_user)
        end
      end

      if @letters and @letters.length > 0 and current_user
        for letter in @letters
          #can't be good performance on long threads.  n+1
          @subscribed = SubscribedLetter.find(:first, :conditions=>["letter_id = ? and user_id = ?",letter.id,current_user.id])
          if @subscribed and @subscribed.read != true
            @subscribed.read = true
            @subscribed.read_on = Time.now
            @subscribed.save!
          end
        end

      end

    end

  end




  def create


  end

  def draft

    User.algolia_reindex!

    @search = User.search("cindy")


    @draft_in_progress = true

    @receiver_id = []

    @user = User.find_by_username(params[:username])


      if @user
        @names = "#{@user.first_name}"
        @receiver_id.push(@user.id)
      else
        @letters = Letter.matching_tag(params[:username]).order_by_date
        if @letters and @letters.length > 0 and current_user
            @names = @letters[0].writing_partner_names(current_user)
            @receiver_id = @letters[0].writing_partner_ids(current_user).dup
        end
      end

    
    @letters = Letter.draft_for(current_user,request.path.gsub(".json",""))
    @letter = @letters .first

    respond_to do |format|
      format.html {
        @page_title = "Draft Letter: #{@names}"

        unless @letter
          @letter = Letter.new
          @letter.author_id = current_user.id
          @letter.salutation = "Hi, #{@names}!"
          for reciever in @receiver_id
            @letter.subscribed_letters.new(letter_id: @letter.id, user_id: reciever)
          end
          #replace with geocode
          @letter.city = "San Francisco"
          #tag re-purposed when draft.  renamed when mailed
          @letter.mailed = false
          @letter.tag = request.path
          @letter.save!
        end
      }
      format.json {

      }
    end
  end


  def save_draft
    @letter = Letter.draft_for(current_user,params[:tag]).first
    @letter.content = params[:draft]
    @letter.save!
    render :text=>"1"
  end

  def mail_letter
    @letter = Letter.find(params[:letter][:id])
     @letter.update_attributes(params[:letter])

    @delivery_date = Time.now + 2.days
    if params[:letter][:delivery_method]
      if params[:letter][:delivery_method] == "Pony Express"
        @delivery_date = Time.now + 3.days
      elsif params[:letter][:delivery_method] == "Stagecoach"
        @delivery_date = Time.now + 5.days
      else
        @delivery_date = Time.now + 10.days
      end
    end

    @letter.participant_ids = @letter.get_participant_ids
    @letter.delivery_date = @delivery_date
    @letter.mailed = true
    @letter.mailed_at = Time.now
    @letter.to_count = @letter.recipients.count

    #should be in model, but had problems saving
    if @letter.recipients.count > 1
      past_letter = Letter.find(:first, :conditions=>["participant_ids = ?",@letter.get_participant_ids])
      if past_letter
        @letter.tag = past_letter.tag
      else
        tag = ""
        for user in @letter.recipients
          tag = "#{tag}#{user.first_name}."
        end
        tag = "#{tag}#{@letter.author.first_name}"
        i = 0;
        @letter.tag = loop do
          if i == 0
            temp_tag = "#{tag}".downcase
          else
            temp_tag = "#{tag}.#{i}".downcase
          end
          i = i + 1
          break temp_tag unless Letter.exists?(tag: temp_tag)
        end
      end
    else
       @letter.tag = @letter.recipients[0].username
    end

    @letter.save!
    @letter.update_sidebar_for_author  
    redirect_to @letter.letter_url_for(current_user)
  end


  def deliver_now

    @letter = Letter.find(params[:id])

    if current_user and current_user.admin and @letter

      @letter.deliver_letter

    end

    render :text=>"Sent"

  end



  def destroy
    @letter = Letter.find(params[:id])
    @letter.destroy
    redirect_to :back
  end

end

app/helpers/letters_helper.rb
module LettersHelper
end

app/views/letters/_letter.html.erb
<%author = false%>

<%if current_user and letter.author%>
	<%if letter.author.id == current_user.id%>
		<%author = true%>
	<%end%>
<%end%>


<%if current_user and letter.delivery_date > Time.now and !author%>
	<%#maybe add a telepgraph message%>
<%else%>

	<div class="letterContainer <%if author%>my_letter<%end%>">

		<div class="letter_content">

			<%if letter.delivery_date > Time.now%>
				<div class="progress_text">
					<div class="progress_label">
						delivery in progress
					</div>
					estimated: <%= letter.delivery_date.strftime("%B %d") %> 

					<%if current_user and current_user.admin%>
						<a class="fa fa-edit"></a>
						<%= link_to '', letter_path(letter), :confirm => 'Are you sure you want to delete this letter?', :class=>"fa fa-times-circle", :method => :delete %>
						<%= link_to '', "/letter/#{letter.id}/deliver_now", :target=>"_blank", :confirm => 'Are you sure you want to deliver this letter?', :class=>"fa fa-plane" %>
					<%end%>

				</div>
			<%end%>

			<%if letter.delivery_method%>
				<div class="stampHolder">
					<img src="/assets/stamp_pony.png" class="stamp">
				</div>
			<%end%>

			<div class="date"><%=letter.city%><br><%= letter.mailed_at.strftime("%B %d, %Y") %></div>

			<%if letter.subject%>
				<br><br><p><b>Re: <%=letter.subject%></b></p>
			<%end%>

			<p><%=letter.salutation%></p>

			<%=raw letter.content%>

		</div>

	</div>
<%end%>

app/views/letters/create.html.erb
<h1>Letters#create</h1>
<p>Find me in app/views/letters/create.html.erb</p>

app/views/letters/draft.html.erb
<div ng-app="slowmail">

	<%#redo when multiple users%>




	<div id="author" ng-view>
		<div class="letterContainer">
			<div class="letter_content">
				<div class="date"><%=@city%><br><%= Time.now.strftime("%B %d, %Y") %></div>
				  <p onclick="alert('More users not supported yet!')" class="to_button"><%=@sal%></p>
				 <textarea id="redactor" name="redactor"><%=current_user.draft%></textarea>
			</div>
		</div>
	</div>

	<div class="hiddenForm" style="display:none">
		<%= form_for @letter, :url => "/mail_letter"  do |f| %>
		  <%= f.hidden_field :id, :value=>@letter.id %> %>
		  <%= f.hidden_field :delivery_method, :value=>"Pony Express" %>
		  <%= f.hidden_field :private, :value=>1%>
		  <%= f.hidden_field :anonymous, :value=>0%>
		  <input type="hidden" id="receiver_id" name="receiver_id" value="<%=@receiver_id.join(",")%>">
		<% end %>
	</div>


	<div style="display:none">

		<div id="MailLetter">

		<script src="//cdn.jsdelivr.net/algoliasearch/3/algoliasearch.min.js"></script>

		<div class="mail_label" style="margin-top:30px">address</div>
		<div style="float:left">
			<div class="another_envelope" >
				<div class="inner">
					<img class="stamp" src="http://www.philatelicdatabase.com/wp-content/uploads/2012/09/stamp-italy-centenary-of-albert-einstein-1979.jpg">
					<div class="return_address">
						<img class="avatar" src="<%=current_user.avatar.gsub("square","large")  %>"> <div class="name"><%=current_user.first_name%>  <%=current_user.last_name%> <br>San Francisco CA</div>
						<div style="clear:both"></div>
					</div>
					<div class="to_address">
						<input class="dotted send_to" placeholder="Full Name" value="<%=@names%>">
						<br>
						<input class="dotted" placeholder="City & State">
					</div>
				</div>
			</div>

			</div>

			<div style="clear:both"></div>

			<div class="mail_label">delivery speed</div>

			<div class="stamp1 delivery_box box_active">
				<img src="/assets/pony.png" style="width:166px; height:125px"><br>
				<b class="delivery_method">Pony Express</b><br>3 days
			</div>

			<div class="stamp2 delivery_box">
				<img src="/assets/stagecoach.png" style="width:182px; height:125px"><br>
				<b class="delivery_method">Stagecoach</b><br>5 days
			</div>

			<div class="stamp3 delivery_box">
				<img src="/assets/clipper.png" style="width:188px; height:125px"><br>
				<b class="delivery_method">Clipper Ship</b><br>10 days
			</div>

			<div style="clear:both"></div>

			<div class="mail_label">privacy</div>
			<div class="privacy_box box_active">
				<b class="privacy_option">Private</b><div style="font-size:12px; margin-top:3px;">Only the recipient can view</div>
			</div>
			<div class="privacy_box">
				<b class="privacy_option">Public, Redacted</b><div style="font-size:12px; margin-top:3px;">Strangers may open, if names redacted</div>
			</div>
			<div class="privacy_box">
				<b class="privacy_option">Public</b><div style="font-size:12px; margin-top:3px;">Random people may heart you</div>
			</div>

			<div style="clear:both"></div>
			<div class="confirm_send">send letter</div> <div class="cancel" onclick="parent.$.fancybox.close();">cancel</div>
			<div style="height:300px"></div>

		</div>
	</div>

	<%if current_user.draft && current_user.draft.length > 0%>
	<script>
	$(".send_letter").addClass("send_letter_active")
	</script>
	 <%end%>
</div>
</div>

app/views/letters/index.html.erb
<%=render :partial=>"web/letters"%>